### ISSUE TITLE
ライセンスについて質問があります

### ISSUE THREAD

**Issue by nandaka-furari** [Hikaru02/open-novel#1]
このリポジトリのコードのライセンスは具体的に何になるのでしょうか？以下の記事、
ライセンスの選択を恐れる必要はありません
http://qiita.com/tadsan/items/99d816e78ca429093b75
を参考にした場合、どれに当たるのでしょうか。

**Comment by kkrrz** [comment]
「お読みください.txt」に詳しく書かれています。
その手の文章は質問する前に読むべきです。

**Comment by nandaka-furari** [comment]
確かに見落としていたと思いますので不注意だったと思いますが、ただ、私の質問は「プログラム」ディレクトリだけでなく、このリポジトリ全体のコード―HTMLやXMLなども含む―についてですし、それについては明記が必要だと思います。
また、通常は、特にGitHubではLICENSE.txt（ファイル名は何でもいいでしょうけれどライセンスについて書いている事が分かる物）などをトップディレクトリに置くことで手間を省くことが多いですので、そうした方がいいように思います。

**Comment by kkrrz** [comment]
> それについては明記が必要だと思います。

必要かどうか決めるのは投稿者です。
GitHubでライセンスの明記は義務付けられていません。

**Comment by nandaka-furari** [comment]
細かいことですが投稿者というよりはリポジトリ管理者でしょうね。ところで管理者は今も活動しているかどうか分からないのですが何かご存知ですか。

**Comment by kkrrz** [comment]
> 細かいことですが投稿者というよりはリポジトリ管理者でしょうね。

わざわざ言い換える必要はありません。
細かいのではなく、無意味な指摘です。

**Comment by nandaka-furari** [comment]
たしかにそうですね。
