### ISSUE TITLE
このプロジェクトに何か手伝えることができないでしょうか

### ISSUE THREAD

**Issue by nandaka-furari** [Hikaru02/open-novel#2]
このプロジェクトに何か貢献できればと思っています。
そして、現在このアプリのコードはほぼJavaScriptで書かれているようです。
（X）HTML、XML、CSSなら分かるのですが、JavaScriptはよく分からないので
現状だと力不足は否めないのですが、自分でも何かしらできることはあると思っています。
もし、前向きに考えてくれるならお返事をお待ちしています。

**Comment by nandaka-furari** [comment]
JavaScriptでデスクトップアプリを作るElectronでの開発を試すためにelectronブランチを作ってみてもらえませんか？ひな型となるファイルをすでに作ってあるのでとりあえずそこにプッシュしたいと思っています。

**Comment by Hikaru02** [comment]
返答が遅くなりすみません。現在プレイヤーをスクラッチから作り直し始めました。
Electronならセキュリティ上の制限も少ないので、開発者にとって有益なものにできるでしょう。
ブランチを分けずにElectronへ対応しようと思っています。

**Comment by nandaka-furari** [comment]
お返事ありがとうございます。大変興味のあるプロジェクトなので推移を見守らせていただきます。うまく進展することを願ってやみません。
